### ISSUE TITLE
GUI 초안 디자인

### ISSUE THREAD

**Issue by fmowl10** [fmowl10/othello-clone#2]

**Comment by Kyoungjinny** [comment]
그리드가 초록,검정일 경우 검정 말이 검정 그리드 위에 위치할 때 구분이 어려울 것 같습니다. 초록, 회색 그리드로 변경하는 것이 어떨까요?

**Comment by fmowl10** [comment]
> 그리드가 초록,검정일 경우 검정 말이 검정 그리드 위에 위치할 때 구분이 어려울 것 같습니다. 초록, 회색 그리드로 변경하는 것이 어떨까요?
제가 게임 판에 대한 이해가 잘못된 것 같군요. 전부 초록색으로 합시다.

**Comment by fmowl10** [comment]
> 그리드가 초록,검정일 경우 검정 말이 검정 그리드 위에 위치할 때 구분이 어려울 것 같습니다. 초록, 회색 그리드로 변경하는 것이 어떨까요?

제가 보드판을 착각하여 말씀드린것 같네요. 전부 초록색이 맞습니다. 전부 초록색으로 하죠 죄송합니다.

**Comment by Kyoungjinny** [comment]
> > 그리드가 초록,검정일 경우 검정 말이 검정 그리드 위에 위치할 때 구분이 어려울 것 같습니다. 초록, 회색 그리드로 변경하는 것이 어떨까요?
> 
> 제가 보드판을 착각하여 말씀드린것 같네요. 전부 초록색이 맞습니다. 전부 초록색으로 하죠 죄송합니다.

네. 수정하겠습니다. 
그래도 비교하여 더 나은걸 선택할 수 있도록 내일 초록,회색 보드판도 보여드리겠습니다.

**Comment by Kyoungjinny** [comment]
![othello](https://user-images.githubusercontent.com/39542951/49126183-fffda880-f305-11e8-849b-f9728740a800.PNG)

일단 이렇게 만들었습니다. 전부 초록색으로 바꾸는 것 외에 더 수정하고 싶으신 점이 있으시다면 말씀해주세요!

**Comment by fmowl10** [comment]
보드판 색이 칙칙하네요. 최대한 원색으로 갑시다. 목요일에 GUI 다른 컴포넌트도 추가 해주세요. 



|   | a | b | c | d | e | f | g | h |
|---|---|---|---|---|---|---|---|---|
| 1 |   |   |   |   |   |   |   |   |
| 2 |   |   |   |   |   |   |   |   |
| 3 |   |   |   |   |   |   |   |   |
| 4 |   |   |   |  ○  | ●  |   |   |   |
| 5 |   |   |   | ●  |  ○  |   |   |   |
| 6 |   |   |   |   |   |   |   |   |
| 7 |   |   |   |   |   |   |   |   |
| 8 |   |   |   |   |   |   |   |   |


○ [(갯수)]                           [(갯수)]●
turn [                                          ]
who win [                                   ]
